apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls # this secret does not exist yet
  issuerRef:
    name: test-selfsigned


# Once the certificate is created, you should see events that confirm that cert is issued
# Events:
#   Type    Reason     Age   From          Message
#   ----    ------     ----  ----          -------
#   Normal  Issuing    33s   cert-manager  Issuing certificate as Secret does not exist
#   Normal  Generated  33s   cert-manager  Stored new private key in temporary Secret resource "selfsigned-cert-8xwgt"
#   Normal  Requested  33s   cert-manager  Created new CertificateRequest resource "selfsigned-cert-shp5q"
#   Normal  Issuing    32s   cert-manager  The certificate has been successfully issued


##### VALIDATE THAT THE SELF SIGNED CERT IS CREATED ######

# apiVersion: v1
# data:
#   ca.crt: 
#   tls.crt: 
#   tls.key: 
# kind: Secret
# metadata:
#   annotations:
#     cert-manager.io/alt-names: example.com
#     cert-manager.io/certificate-name: selfsigned-cert
#     cert-manager.io/common-name: ""
#     cert-manager.io/ip-sans: ""
#     cert-manager.io/issuer-group: ""
#     cert-manager.io/issuer-kind: Issuer
#     cert-manager.io/issuer-name: test-selfsigned
#     cert-manager.io/uri-sans: ""
#   creationTimestamp: "2022-03-31T05:37:37Z"
#   name: selfsigned-cert-tls
#   namespace: cert-manager-test
#   resourceVersion: "324581"
#   uid: d12f5a66-1aef-4faa-8ad0-c6909bf7c39b
# type: kubernetes.io/tls